

DROP TABLE IF EXISTS `MY_RECIPE`;
DROP TABLE IF EXISTS `ITEM_PHOTO`;
DROP TABLE IF EXISTS `CATEGORY`;
DROP TABLE IF EXISTS `FILE`;
DROP TABLE IF EXISTS `ITEM`;
DROP TABLE IF EXISTS `fridge`;
DROP TABLE IF EXISTS `MEMBER`;



CREATE TABLE `MEMBER` (
	`MEMBER_NO`	INT	NOT NULL	COMMENT 'SEQUENCE',
	`ID`	VARCHAR(20)	NOT NULL,
	`PASSWORD`	VARCHAR(20)	NOT NULL,
	`NAME`	VARCHAR(20)	NULL,
	`NICKNAME`	VARCHAR(20)	NULL,
	`PHONE`	VARCHAR(20)	NULL,
	`GENDER`	CHAR(1)	NULL,
	`EMAIL`	VARCHAR(50)	NULL,
	`ENROLL_DATE`	DATE	NULL,
	`MEMBER_STATUS`	CHAR(1)	NULL	DEFAULT 'Y',
	`USER_TYPE`	VARCHAR(5)	NOT NULL	DEFAULT 'U'
);


CREATE TABLE `MY_RECIPE` (
	`RECIPE_NO`	INT	NOT NULL,
	`MEM_NO`	INT	NOT NULL,
	`FARM_NAME`	VARCHAR(30)	NOT NULL,
	`LOCAL_CODE`	VARCHAR(20)	NULL,
	`ADDRESS`	VARCHAR(100)	NOT NULL,
	`PHONE`	VARCHAR(20)	NOT NULL,
	`ENROLL_DATE`	DATE	NULL,
	`STATUS`	CHAR(1)	NULL	DEFAULT 'Y'	COMMENT '농장삭제여부',
	`FARM_IMAGE`	VARCHAR(50)	NULL,
	`CROP`	VARCHAR(30)	NULL
);


CREATE TABLE `FILE` (
	`FILE_NO`	INT	NOT NULL,
	`ORIGIN_NAME`	VARCHAR(100)	NULL,
	`CHANGE_NAME`	VARCHAR(100)	NULL,
	`UPLOAD_DATE`	DATE	NULL,
	`STATUS`	CHAR(1)	NULL	DEFAULT 'Y'	
);




CREATE TABLE `fridge` (
	`FRIDGE_NO`	VARCHAR(255)	NOT NULL,
	`MEMBER_NO`	INT	NOT NULL	COMMENT 'SEQUENCE',
	`FRIDGE_NAME`	VARCHAR(30)	NOT NULL COMMENT '회원번호+냉장고명 복합키(UNIQUE)',
	`STATUS`	INT	 NULL
);



CREATE TABLE `ITEM` (
	`ITME_NAME`	VARCHAR(100)	NOT NULL,
	`BARCODE`	INT	NULL,
	`PRICE`	VARCHAR(30)	NULL,
	`CONDITION`	VARCHAR(20)	NOT NULL	COMMENT 'FRIDGE / FREEZER / ROOM',
	`EXP_DATE`	DATE	NOT NULL	COMMENT '제품명+유통기한: 복합키 (UNIQUE)[',
	`MEMO`	VARCHAR(20)	NULL,
	`ITEM_PHOTO`	VARCHAR(50)	NULL,
	`ENROLL_DATE`	DATE	NULL,
	`STATUS`	CHAR(1)	NULL	DEFAULT 'Y',
	`INT`	FLOAT	NOT NULL,
	`ITEM_CATEGORY`	VARCHAR(20)	NOT NULL
);



CREATE TABLE `CATEGORY` (
	`CATEGORY`	VARCHAR(20)	NOT NULL
);

CREATE TABLE `ITEM_PHOTO` (
	`FILE_NO`	INT	NOT NULL,
	`ITME_NAME`	VARCHAR(100)	NOT NULL
);

ALTER TABLE `MEMBER` ADD CONSTRAINT `PK_MEMBER` PRIMARY KEY (
	`MEMBER_NO`
);

ALTER TABLE `MY_RECIPE` ADD CONSTRAINT `PK_MY_RECIPE` PRIMARY KEY (
	`RECIPE_NO`
);


ALTER TABLE `FILE` ADD CONSTRAINT `PK_FILE` PRIMARY KEY (
	`FILE_NO`
);

ALTER TABLE `fridge` ADD CONSTRAINT `PK_FRIDGE` PRIMARY KEY (
	`FRIDGE_NO`
);


ALTER TABLE `CATEGORY` ADD CONSTRAINT `PK_CATEGORY` PRIMARY KEY (
	`CATEGORY`
);

ALTER TABLE `fridge` ADD CONSTRAINT `FK_MEMBER_TO_fridge_1` FOREIGN KEY (
	`MEMBER_NO`
)
REFERENCES `MEMBER` (
	`MEMBER_NO`
);

ALTER TABLE `PHOTO` ADD CONSTRAINT `FK_CATEGORY_TO_PHOTO_1` FOREIGN KEY (
	`ITEM_CATEGORY`
)
REFERENCES `CATEGORY` (
	`CATEGORY`
);

ALTER TABLE `ITEM_PHOTO` ADD CONSTRAINT `FK_FILE_TO_ITEM_PHOTO_1` FOREIGN KEY (
	`FILE_NO`
)
REFERENCES `FILE` (
	`FILE_NO`
);

ALTER TABLE `ITEM_PHOTO` ADD CONSTRAINT `FK_PHOTO_TO_ITEM_PHOTO_1` FOREIGN KEY (
	`ITME_NAME`
)
REFERENCES `PHOTO` (
	`ITME_NAME`
);
